# Generated by Django 4.2 on 2023-04-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mk', '0006_newsletteruser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletteruser',
            old_name='email',
            new_name='user_email',
        ),
    ]
